### ISSUE TITLE
Exception when running with ToTask()

### ISSUE THREAD

**Issue by vpenades** [Cysharp/ProcessX#10]
When I run this line:

```c#
            var psi = CreateStartInfo(...);

            var lines = await Cysharp.Diagnostics.ProcessX
                .StartAsync(psi)
                .ToTask(token);            

            var text = string.Join("\r\n", lines);
```

I get this exception:

    Cysharp.Diagnostics.ProcessErrorException : Process returns error, ExitCode:0

```
AsyncOperation`1.GetResult(Int16 token)
ProcessAsyncEnumerator.MoveNextAsync()
ProcessAsyncEnumerable.ToTask(CancellationToken cancellationToken)
ProcessAsyncEnumerable.ToTask(CancellationToken cancellationToken)
...
```

When calling syncronously, everything works fine.

Steps to reproduce:
- clone https://github.com/vpenades/GltfValidator.git
- run test Test1Async

**Comment by neuecc** [comment]
thanks for reporting.
However can not find Test1Async code in your repository.

**Comment by vpenades** [comment]
here's the link for [Test1Async](https://github.com/vpenades/GltfValidator/blob/64dd150a450a59f1ed58a116b473e0a5462556e7/src/GltfValidator.Tests/UnitTest1.cs#L28)

**Comment by neuecc** [comment]
Currently if data exists in StdError, ProcessX throws error.
If you want to ignore stderror result, use GetDualAsyncEnumerable.

```csharp
public static async Task<ValidationReport> ValidateFileAsyncProcessX(string gltfFilePath, System.Threading.CancellationToken token)
{
    var psi = CreateStartInfo(gltfFilePath);
    var (_, stdout, stderror) = Cysharp.Diagnostics.ProcessX.GetDualAsyncEnumerable(psi);
    var lines = await stdout.ToTask(); // ignore stderror

    return ValidationReport.Parse(string.Join("\r\n", lines));
}
```

**Comment by vpenades** [comment]
That solved the problem, thanks for the fast reply!
