### ISSUE TITLE
Reading large byte data

### ISSUE THREAD

**Issue by LadislavBohm** [Cysharp/ProcessX#15]
I'm trying to call process that for example compresses large data or does some video processing. This process outputs large stream of data that I would like to process it in C# ideally as some sort of a stream.

Is there a way to achieve this in ProcessX or is it something where I have should go to .NET Process class and read standard output myself?

**Comment by neuecc** [comment]
I don't have it right now, but it would be nice to have something like WriteBinaryAsync, similar to StartReadBinaryAsync.
Thank you
