### ISSUE TITLE
Add standard error redirect option

### ISSUE THREAD

**Issue by itn3000** [Cysharp/ProcessX#2]
Currently(rev: https://github.com/Cysharp/ProcessX/commit/09f95cb0cb17ecd5499284dbefb809207c44334e), ProcessX.StartAsync throws error when process output stderr.
This may be unexpected result in apps using stderr as logging or progress.

So I propose adding option to redirecting stderr.
In particular, add `System.IO.Stream` or `System.Buffers.IBufferWriter<byte>`(or `char`?) to `ProcessX.StartAsync` API

**Comment by neuecc** [comment]
thanks for the proposal.
I've added new api `GetDualAsyncEnumerable`, and just published in `1.1.0`.
https://github.com/Cysharp/ProcessX#raw-processstderror-stream

Is it okay?

**Comment by itn3000** [comment]
This is what I needed, thanks.

**Comment by bent-rasmussen** [comment]
Just an idea - a combined async enumerable:

```csharp
struct ProcessResponse
{
	public ProcessResponse(ProcessResponseSource source, string text)
	{
		Source = source;
		Text = text;
	}

	public ProcessResponseSource Source { get; }
	
	public string Text { get; }
}

public enum ProcessResponseSource
{
	Output,
	Error,
}

```
