### ISSUE TITLE
run process with a CancellationToken

### ISSUE THREAD

**Issue by vpenades** [Cysharp/ProcessX#9]
it could be nice if methods could allow passing a CancellationToken so they can be cancelled from the outside.

**Comment by neuecc** [comment]
Would `withCancellation` helps it?

**Comment by vpenades** [comment]
Ah, yes, I didn't realize that extension... neat!

**Comment by ZzZombo** [comment]
But it is only for the async. enumerator version? Why is there no support for that in `WaitAsync()`?
